### ISSUE TITLE
Equipo de futbol

### ISSUE THREAD

**Issue by fmigliavacca** [pdepjm/2024-tp0-presentacion-tommyrios#1]
Hola Tomy, me parece que todos queremos saber de qué equipo de futbol sos. Si pudieras comentarlo en tu read-me estaría buenísimo. Saludos crack!

**Comment by tommyrios** [comment]
Hola Fede, que tal? Gracias por tu aporte, ya lo agrego!

**Comment by tommyrios** [comment]
Hola Fede, que tal? Gracias por tu aporte, ya lo agrego!
