### ISSUE TITLE
Recomendación

### ISSUE THREAD

**Issue by GonzaGalarza** [pdepjm/2024-tp0-presentacion-tommyrios#3]
Buenas tommy, estaba revisando tu presentación y me parece que a la misma le falta una imagen de tu persona.

**Comment by tommyrios** [comment]
Buenas Gonza, tenes razón, ya lo agrego. Gracias!

**Comment by tommyrios** [comment]
Buenas Gonza, tenes razón, ya lo agrego. Gracias!
